export { default as Home } from './Home'
export { default as Education } from './Education'
export { default as Projects } from './Projects'
export { default as Resume } from './Resume'
export { default as More } from './More'